### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by MasterCoder21** [BananikXenos/UDPPacketer#1]
Any idea how one would port forward a server made with this utility?  I’m new to networking so sorry if this is a stupid question 🤷‍♂️

**Comment by MasterCoder21** [comment]
I’d like to port forward so that other users of my client could connect to my client server (hosted locally) for cosmetics, friends, etc.

**Comment by BananikXenos** [comment]
Every router has it different. But what you can to is open your Command Prompt and type in ipconfig. Then search for your Default Gateway. (Ex. mine is 192.168.1.1). Now go to your browser and type in the address box 192.168.1.1 (Your gateway). Now the login of the router should show up. Type in the credentials of your router (If you don't know them, check on the bottom of your router, or search for the default on the internet for your router) Now you need to search for The port forwarding. (I recommend you to search this up for your router). ![Untitled](https://user-images.githubusercontent.com/78347016/185201652-0894bdfa-3065-466c-a4ff-8524fd410f8e.png) My port forwarding is in Security > Port Forwarding. When you find it you will need add new port forwarding. Type in the field name of the port forwarding (anything you want) and IP of the machine you are port forwarding (You can find this: Open Command Prompt [on the pc you are going to host the server] and type ipconfig and find  IPv4 Address of your adapter) then type in the port you are hosting it and save. It will take a few seconds to apply. You can find more info on this site I found https://www.lifewire.com/how-to-port-forward-4163829.
Then to get the IP you forwarded go to https://www.whatismyip.com/ and use this in the client constructor, with the port. You can check the Client Example in this repo.

Hope this helps!

**Comment by MasterCoder21** [comment]
Awesome, thanks so much!
