### ISSUE TITLE
Multiple listeners support & changing how packets are read

### ISSUE THREAD

**Issue by MasterCoder21** [BananikXenos/UDPPacketer#2]
Hi there again!  I was looking through the new update, and I can’t wait to implement this in my client!  However, I noticed one thing that isn’t supported that I think would be a great addition to this utility, which is adding multiple listeners to both a client and a server.  Right now, you have to handle all your packets through one listener, which may get messy.  Changing the line that holds just one listener to a list of listeners would make handling packets a lot easier.

Now on to reading packets.  Currently, there is no method in the Packet interface for reading a packet, just writing a packet.  This makes defining serverbound vs. clientbound packets really hard to differentiate.  Also, I noticed that my IDE complained unless each packet I made had a constructor with a single DataInputStream parameter.  Changing the way packets are read (not constructed) to using a read() method (like Minecraft packets) may make packet handling a lot easier.

Thanks!

**Comment by BananikXenos** [comment]
Hello, thank you for the great idea 😃. I will implement the multiple listeners and the constructor as soon as can. The multiple listeners is a simple but crucial feature that i somehow forgot to add. I will add these features tomorrow in the morning. And thanks for using the library and making it better ☺ After these features i will start working an packet reliability. I will add system like in TCP for ensured packet delivery. So you can post unreliably (like cosmetics player have, that you can resend) and reliably (login credentials, send chat message etc.)

**Comment by MasterCoder21** [comment]
Lol no problem, I've been in need of a good websocket/packet system for my client and was finally able to implement some online features in clients such as Lunar!  Thanks for taking my suggestions into consideration :)

**Comment by BananikXenos** [comment]
Done 👍 Just use the new Release v2.1 and check the [wiki](https://github.com/BananikXenos/UDPPacketer/wiki) if you face any issues or DM me on discord Synse#3191
